spring:
  datasource:
    url: jdbc:mysql://sql.pixmoto.loc/development
    username: developer
    password: StarS33d
    driver-class-name: com.mysql.jdbc.Driver

security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      scope: read,write
      auto-approve-scopes: '.*'